dist: trusty
sudo: false
language: node_js
node_js:
- '12'
cache:
  directories:
  - "./node_modules"
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: JcN8/dCmb8TnPQxB0MYUEh+1cwUSBuIYUdQxqnvHryItM0vA8LKQ4YHRlLaApBAdAF484enq1bSvMJNoM/rPOhrDMu1nKwLCT99idkpVyAP9BOnGn9S5iitXQsEuQB0L0x/mTqlZU71P4wkAg+SupUNE2o2ePDTWle7/Zpq/87ofvWsKBLQMOUuHR0Je4W2WRTYw/tbQE01gJet97H66w8RJtb/yWiwNjs/UEmBhlwsP1YEjTfuhgTQxXgkRP+IWr5amw7hAgTXcGu/seAQ0LEoSwvnGVaJSgFaGVBeXD1w30WjC7vZgXTmfD/Mkdg+8lm/YwHo9rJeMlzO5E3+nDRSaqtEQnLxKkLbgwH/v1aHGQNh4k2182DNvs7tdpqf0zVtXxU7lDT0CUOF4PeJZ/P+jlEx3urMvyaYi1rsv6RBQYKjzM/FzJAyKO4TxkRyxTCQbD8o91DuCpeUcGgKz/ofKNIvDOo7+6Zl43yc+omu7MexZLtY5nWmBKkwfTF/ZriLa106F/UosCnygmX0EFenep/r92UMyez82US78nvetE/tRqAaUbASvbXi6SMxzV2c6Vs/IYHEbx56uwQxOvDTrwcOUP9jS+Qno6yRfujyMHm+Y9Ips+HKKXb23USfsbMY3U7je0Li4KzcbbqJmsXhDv1cvzGSoNokYGF+mJZY=
  app: aspirajato
  on:
    branch: dev
