dist: trusty
sudo: false
language: node_js
node_js:
- '12'
cache:
  directories:
  - "./node_modules"
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: i1/hi4weA6qxZ01i6mzOCrrRxcOXDpacFszXYv85SXlnVGZbUjY5xr27IJLB528+5tSvkMQc84ibkcDzDPyud6Y8HmlgXpsHNjM4bgXv/oADr1ZMPJzU1H+1FJbSw5SnogBztTa7AWgFrVyZJqfT0TZEkkMuRoY/MKo/0Zv+TnNxxMH/gB8kY2oTIEYZBFQ8nps3KB7ZivT31m3V7SuLGDsYuwbjbWKs2PE1p4BlvijMpnmUeUc3xEffi0FnSvjfiUz9BYdzbZ86hhzvsph0oaPJc9AbAoUdjaYnG/ctltmVIBefQVd4WHlB+hGZZJlUAis52ageZpAv4ThZviWZ5xzTyoQ4Kf7FXQcVa2Rejg/NCz/x45Jf1nkpZ6DokXXejnRM1DYp00w7yICDjouMQVMfdmbyi13CK6K6ZrpiPHVk3F4SS54NSBY6RLgeSWazDwvYvjeOzlsukHsY/CmXrd2ZdTJCBv0vWzuzCliIBPeGpq2Z9gVfQF/BoCDQBAf/ZWTgiDAzK78ghkcwNAA5WKSoVSqhXOkcEcu0zulEBKT3YDUj18BINR66O957my8fV73KZO1viFHBxCoWUdeIFq920uAC5DeFNfZE2P0zP6NuS1nSVqJo8dGmh3JcsvAx4TevGBlfqxwVGSQEhnu7qlU2EP1FCgLi+QB+N5E872g=
  app: aspirajato
  on:
    branch: dev
